### ISSUE TITLE
Integrating back into main vue repo.

### ISSUE THREAD

**Issue by blocka** [SmallComfort/react-vue#1]
Wow. This seems like a real game changer to me! Biggest downside is that you had to fork vue for this. Do you have any thoughts on submitting this back as a PR to vue?

**Comment by SmallComfort** [comment]
react-vue only use the reactivity system of vue, the rest is react. In fact, as long as vue exposed the Watcher function, you can use vue to drive react directly. On the other hand, loading an entire vue in the react may increase the size of your application. But this goal at least appears feasible, such as export the reactivity system by the vue self.

**Comment by blocka** [comment]
Isn't this repo the whole vue?

**Comment by SmallComfort** [comment]
yeah, It only uses the files in ```./src/core/*```

**Comment by iBobik** [comment]
How about some cleanup? To make it small module without not needed Vue files.
