### ISSUE TITLE
Is "vue-react" reverse of "react-vue" possible here?

### ISSUE THREAD

**Issue by TheLarkInn** [SmallComfort/react-vue#4]
Is it possible through this library to: 

* import a react component into a vue application

**Comment by SmallComfort** [comment]
Hi! I'm sorry to reply to you until now.

react-vue can not import a react component into a vue application.

Use react-vue, All the code truly runs in React runtime, that's a React application.

**Comment by faceyspacey** [comment]
@TheLarkInn there's https://github.com/alkin/vue-react , but as you can see from its one source file it's not doing nearly as much as this package is doing in reverse:

https://github.com/alkin/vue-react/blob/master/src/vue-react.js

😎
