### ISSUE TITLE
Is it possible to upgrade the react-native version to the latest version?

### ISSUE THREAD

**Issue by chuanhaisoft** [SmallComfort/react-vue#8]
Is it possible to upgrade the react-native version to the latest version?

to  0.55.1

**Comment by SmallComfort** [comment]
你好！
react-vue 并不依赖 react-native 的某一个特定版本，有没有更详细的 demo 用例？

**Comment by chuanhaisoft** [comment]
我把 HackerNews/package.json   里面的 "react-native": "^0.44.0" 改成 0.55.1后，虽然编译过去了，但是app提示错误，Requiring module "260",which threw an exception : Error:Requiring module "169"...................................      等的错误信息

新建了一个项目可以了
